package com.os.utility;

/**
 * Created by Jin on 2014/9/10.
 */
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;

public class DatabaseHelper extends SQLiteOpenHelper {
    private static int VERSION = 1;
    private static String CREATE_USERINFO_TABLE = "create table userinfo(_id INTEGER PRIMARY KEY,username text,password text)";
    private static String CREATE_BOARD_TABLE = "create table board(_id INTEGER PRIMARY KEY,english text,chinese text)";
    private static String CREATE_FAV_TABLE = "create table fav(_id INTEGER PRIMARY KEY,english text,chinese text,islocal integer)";
    private static String CREATE_SETTING_TABLE = "create table settings(_id INTEGER PRIMARY KEY,key text,value text)";
    private static String CREATE_BLOCK_TABLE = "create table block(_id INTEGER PRIMARY KEY,name text)";

    public DatabaseHelper(Context context, String name, CursorFactory factory,
                          int version) {
        super(context, name, factory, version);
    }

    public DatabaseHelper(Context context,String name,int version) {
        this(context,name,null,version);
    }

    public DatabaseHelper(Context context,String name) {
        this(context,name,VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL(CREATE_USERINFO_TABLE);
        db.execSQL(CREATE_BOARD_TABLE);
        db.execSQL(CREATE_FAV_TABLE);
        db.execSQL(CREATE_SETTING_TABLE);
        db.execSQL(CREATE_BLOCK_TABLE);
        String [] settingArray = getSettingArray();
        String [] boardArray = getBoardArray();
        for(int i = 0; i < settingArray.length; i++) {
            db.execSQL("INSERT INTO settings(key, value) VALUES " + settingArray[i]);
        }
        for(int i = 0; i < boardArray.length; i++) {
            db.execSQL("INSERT INTO board (english, chinese) VALUES " + boardArray[i]);
        }
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }

    private String [] getSettingArray() {
        return new String[] {"('sign', 'Sent From My Android Client.')",
                             "('isLogin', '0')",
                             "('isShowPic', '1')",
                             "('isSavePic', '1')",
                             "('isSendMail', '0')",
        };
    }

    private String[] getBoardArray() {
        return new String[] {"('1937_12_13', '南京大屠杀')",
                             "('7th_Art', '第七艺术')",
                             "('Abroad', '飞越重洋')",
                             "('AcademicReport', '学术讲座')",
                             "('Actuary', '保险精算')",
                             "('AD_Art', '广告艺术')",
                             "('Advice', '百合共创')",
                             "('Aerospace', '宇航')",
                             "('Agent', '代理')",
                             "('AI', '人工智能')",
                             "('AlbumShow', '个人写真')",
                             "('Algorithm', '算法')",
                             "('America', '美利坚之窗')",
                             "('AnHui', '淮水皖风')",
                             "('Announce', '站务公告栏')",
                             "('AntiMalfeasant', '反腐倡廉')",
                             "('AntiRumor', '反谣言中心')",
                             "('Apple', '苹果电脑')",
                             "('Archaism', '古文观止')",
                             "('Archeology', '考古')",
                             "('ASCIIArt', 'ASCII艺术')",
                             "('Association_Union', '社团联合会主席信箱')",
                             "('Astrology', '星月童话')",
                             "('AtmosphereSci', '大气科学论坛')",
                             "('AutoSpeed', '车迷世界')",
                             "('Badminton', '羽毛球')",
                             "('Basketball', '篮球')",
                             "('BBSDev', 'BBS的安装与设置')",
                             "('BBSHelp', '新手求助')",
                             "('bbslists', '本站的各类统计列表与记录')",
                             "('BeiJing', '首都北京')",
                             "('Billiards', '台球')",
                             "('BitTorrent', '比特洪流')",
                             "('Bless', '温馨祝福')",
                             "('Blog', '博客论坛')",
                             "('BMManager', '版主监督和管理')",
                             "('BNGames', '南大战网游戏')",
                             "('Board', '版主竞选与请辞')",
                             "('BoardGame', '桌面游戏')",
                             "('BoardManage', '版面开设与变更')",
                             "('BodilyForm', '高矮胖瘦')",
                             "('Borland', 'Borland世界')",
                             "('Bowling', '保龄球馆')",
                             "('Boxing_Fight', '拳击与格斗')",
                             "('Boys', '男生世界')",
                             "('Bridge', '桥牌联谊会')",
                             "('Britain', '行走英伦')",
                             "('Budaixi', '布袋戏')",
                             "('bulletin', '校务公告')",
                             "('C_Inter', '国际学院')",
                             "('Calligraphy', '中国书法')",
                             "('CAS', '中国科学院')",
                             "('CCAS', '中美中心')",
                             "('CCP', '礼仪中心')",
                             "('CFD', '计算流体论坛')",
                             "('ChangZhou', '锦绣常州')",
                             "('Chat', '聊天版')",
                             "('Chemistry', '化学版')",
                             "('Chess', '象棋')",
                             "('ChinaFootball', '中国足球')",
                             "('ChinaNews', '国内新闻')",
                             "('Chorus', '声乐艺术爱好者（南大合唱团）')",
                             "('Chrematistics', '理财')",
                             "('Christianity', '基督教研究')",
                             "('ChunQiu_ZhanGuo', '春秋战国 ')",
                             "('Civil_Servant', '公务员之家')",
                             "('Classical_Poem', '古典诗词')",
                             "('ClassicalCulture', '古韵悠长')",
                             "('ClassicalMusic', '古典音乐')",
                             "('Collections', '收藏爱好')",
                             "('Comic', '动漫世界')",
                             "('Complain', '投诉与举报')",
                             "('Computer_ABC', '电脑菜鸟要学飞')",
                             "('Consultant', '咨询')",
                             "('Contest', '大学生竞赛')",
                             "('Couplet', '对联')",
                             "('CPA', '注册会计师')",
                             "('CPlusPlus', 'C++程序设计语言')",
                             "('CPU', '中国药科大学')",
                             "('Cross_Strait', '穿越海峡')",
                             "('CrossShow', '十字绣坊')",
                             "('Cube', '魔方')",
                             "('CUG', '中国地质大学')",
                             "('CUMT', '中国矿业大学')",
                             "('Cycling', '自行车运动')",
                             "('D_Chinese', '中文系')",
                             "('D_Computer', '计算机系')",
                             "('D_EarthScience', '地球科学与工程学院')",
                             "('D_EE', '电子科学与工程学院')",
                             "('D_History', '历史系')",
                             "('D_Materials', '材料科学系')",
                             "('D_Maths', '数学系')",
                             "('D_Philosophy', '哲学系')",
                             "('D_Physics', '物理学院')",
                             "('D_SocialSec', '社会保障系')",
                             "('Dance', '舞蹈天地')",
                             "('Database', '数据库系统')",
                             "('Debate', '辩者无敌')",
                             "('Detective', '侦探推理')",
                             "('Deutsch', '德文堂')",
                             "('DigiMusic', '数码音乐设备')",
                             "('DigitalWorld', '数码世界')",
                             "('DII', '匡亚明学院_强化部')",
                             "('Discovery', '神秘之旅')",
                             "('DiscZone', '碟碟不休')",
                             "('DongBei', '白山黑水')",
                             "('DotaAllstars', '远古之守护')",
                             "('DotNet', '.net技术')",
                             "('Drama', '戏剧春秋')",
                             "('Drawing', '绘画艺术')",
                             "('Dream', '青春有梦')",
                             "('Drink', '酒吧与咖啡馆')",
                             "('DV_Studio', 'DV工作室')",
                             "('E_Business', '电子商务特区')",
                             "('E_Sports', '电子竞技')",
                             "('EarthSciences', '地球科学')",
                             "('Economics', '经济学')",
                             "('Education', '教育论坛')",
                             "('EEtechnology', '电子技术版')",
                             "('ElectronicMusic', '电子音乐')",
                             "('Embedded', '嵌入式系统')",
                             "('Emprise', '武侠小说')",
                             "('English', '英语世界')",
                             "('EnglishCorner', '英语聊天版')",
                             "('Esperanto', '世说新语')",
                             "('Esquire', '时尚男生')",
                             "('ExcellentBM', '版务评优')",
                             "('ExchangeStudent', '交换生天地')",
                             "('F1', '一级方程式赛车')",
                             "('F_Literature', '外国文学')",
                             "('FairyTale', '七色花')",
                             "('FamilyLife', '家庭生活')",
                             "('FanBu', '反哺学社')",
                             "('Fantasy', '奇幻天地')",
                             "('Fashion', '美丽流行风')",
                             "('FDU', '复旦大学')",
                             "('FEA', '对外交流协会')",
                             "('Feelings', '感情世界')",
                             "('Fiction', '科幻世界')",
                             "('Finance', '金融天下')",
                             "('Fishing', '碧波垂钓')",
                             "('Fitness', '健美与健身')",
                             "('Flash', '闪客世界')",
                             "('FleaMarket', '跳蚤市场')",
                             "('Flowers', '花草园艺')",
                             "('Folk_Country', '民谣及乡村音乐')",
                             "('Folk_Music', '国乐飘香（民乐团）')",
                             "('FOOD', '雅舍谈吃')",
                             "('Fortran', 'Fortran语言')",
                             "('Forum', '百合论坛')",
                             "('French', '浪漫法兰西')",
                             "('Friendship', '友情久久')",
                             "('FuJian', '八闽畅怀')",
                             "('GAFA', '天文爱好者协会')",
                             "('GEC', '研究生英语俱乐部')",
                             "('Geography', '地理科学')",
                             "('Girls', '女生天地')",
                             "('GIS', '地理信息科学')",
                             "('GJ', '够级艺术')",
                             "('GoToUniversity', '高考招生信息')",
                             "('Graphics', '电脑图形处理')",
                             "('GRE_TOEFL', 'GRE&TOEFL专题讨论')",
                             "('GreatTurn', '脑筋急转弯')",
                             "('GreeceRome', '希腊罗马')",
                             "('GreenEarth', '南大环境保护协会')",
                             "('GuangDong', '粤是故乡名')",
                             "('GuangXi', '八桂大地')",
                             "('Guilt', '罪与罚')",
                             "('Guitar', '吉它')",
                             "('GuQin', '古琴社')",
                             "('Hacker', '黑客的摇篮')",
                             "('HaiNan', '天涯海角')",
                             "('HandiCraft', '精致手工')",
                             "('Hardware', '硬件工作室')",
                             "('HeBei', '燕赵大地')",
                             "('HeNan', '九州之中')",
                             "('HHU', '河海大学')",
                             "('HiFi', '发烧天堂')",
                             "('History', '历史')",
                             "('HKU', '香港大学')",
                             "('Hometown', '游子情深')",
                             "('HomoSky', '同一片天空')",
                             "('HotZone', '战场')",
                             "('HPC', '高性能计算')",
                             "('HuaiAn', '淮水楚云')",
                             "('HuBei', '荆楚大地')",
                             "('Human', '人类漫谈')",
                             "('HuNan', '三湘四水')",
                             "('ID', '掀起你的盖头来')",
                             "('IELTS', '清谈雅思')",
                             "('IFA_IS', '美术研究院_雕塑艺术研究所')",
                             "('IFIS', '海外教育学院')",
                             "('Image', '图像世界')",
                             "('Info_Manage', '信息管理技术')",
                             "('Inner_Mongolia', '塞外风情')",
                             "('Intern', '实习')",
                             "('IR', '国际关系')",
                             "('ITClub', 'IT俱乐部')",
                             "('ITExam', 'IT认证考试')",
                             "('J_Ent', '和风艺影')",
                             "('Japanese', '日语学习')",
                             "('Java', 'Java语言')",
                             "('Jazz_Blues', '爵士蓝调')",
                             "('JiangXi', '江南西道')",
                             "('JLU', '吉林大学')",
                             "('JobAndWork', '创业与求职')",
                             "('JobExpress', '就业特快')",
                             "('Joke', '笑话版')",
                             "('Journalism', '新闻传播研究')",
                             "('JSSports', '江苏体育')",
                             "('KaoYan', '考研天地')",
                             "('KaraOK', '卡拉永远OK')",
                             "('Korea', '恋恋韩风')",
                             "('Law', '法律学')",
                             "('LectureHall', '学术交流')",
                             "('LianYunGang', '花果山下')",
                             "('Life', '生活')",
                             "('LifeLeague', '生命协会')",
                             "('LifeScience', '生命科学')",
                             "('LilyDigest', '百合精华')",
                             "('LilyFestival', '百合站庆')",
                             "('LilyLinks', '百合友情链接')",
                             "('LilyStudio', '小百合工作室项目反馈')",
                             "('Linguistics', '语言与语言学')",
                             "('LinuxUnix', 'Linux和Unix')",
                             "('LostToFind', '失物招领')",
                             "('Love', '情爱悠悠')",
                             "('LSCMA', '物流与供应链管理协会')",
                             "('LZU', '兰州大学')",
                             "('M_Academic', '教务处处长信箱')",
                             "('M_CMHER', '心理中心主任信箱')",
                             "('M_Gonghui', '工会主席信箱版')",
                             "('M_Graduate', '研究生院院长信箱')",
                             "('M_GraduateUnion', '研究生会主席信箱')",
                             "('M_Guard', '保卫处处长信箱')",
                             "('M_Hospital', '校医院院长信箱')",
                             "('M_Job', '就业创业指导中心主任信箱')",
                             "('M_League', '团委书记信箱')",
                             "('M_Library', '图书馆馆长信箱')",
                             "('M_Logistic', '后勤工作信箱')",
                             "('M_NIC', '网络中心主任信箱')",
                             "('M_Student', '学生工作处处长信箱')",
                             "('M_StudentUnion', '学生会主席信箱')",
                             "('Magic', '魔术')",
                             "('MaJiang', '麻将')",
                             "('Management', '管理学')",
                             "('MARC', '模式动物研究所')",
                             "('Marketing_Zone', '营销学社')",
                             "('Marvel', '鬼故事')",
                             "('Mathematics', '数学版')",
                             "('MathTools', '数学工具软件')",
                             "('Mediastudy', '媒介文化研究')",
                             "('Medicine', '医学与健康')",
                             "('Memory', '似水流年')",
                             "('Microwave', '电磁场与微波技术')",
                             "('Military', '军事科学')",
                             "('Mobile', '手机天地')",
                             "('Model_Space', '模型空间')",
                             "('Modern_Poem', '现代诗歌')",
                             "('Movies', '露天电影院')",
                             "('MSTClub', '微软技术俱乐部')",
                             "('MSWindows', '美丽的微软窗口')",
                             "('MudLife', 'MUD人生')",
                             "('Musical', '音乐剧之家')",
                             "('Mythlegend', '神话传说')",
                             "('Names', '姓名文化')",
                             "('NanJing', '古都南京')",
                             "('NanoST', '纳米科技')",
                             "('NanTong', '江风海韵')",
                             "('Nature', '人与自然')",
                             "('NetResources', '网络资源')",
                             "('Network', '网络世界')",
                             "('NewAge', '新世纪音乐')",
                             "('newcomers', '新手上路')",
                             "('Nirvana', '桫椤双树园')",
                             "('NJ_HOUSE', '房屋租赁')",
                             "('NJAU', '南京农业大学')",
                             "('NJMU', '南京医科大学')",
                             "('NJNU', '南京师范大学')",
                             "('NJU_Graduate', '南大研究生报')",
                             "('NJU_HOME', '南大和园')",
                             "('NJU_TIC', '南京大学腾讯创新俱乐部')",
                             "('NJU_Youth', '南大青年报')",
                             "('NJU_zhixing', '南京大学知行社')",
                             "('NJUExpress', '南大校园生活')",
                             "('NJUMUN', '模拟联合国协会')",
                             "('NJUPT', '南京邮电大学')",
                             "('NJUT', '南京工业大学')",
                             "('NKU', '南开大学')",
                             "('NoteBook', '本本梦工厂 ')",
                             "('notepad', '酸甜苦辣留言版')",
                             "('Novel', '小说')",
                             "('NUAA', '南京航空航天大学')",
                             "('NUST', '南京理工大学')",
                             "('NZY', '南京中医药大学')",
                             "('OfficeStaff', '上班一族')",
                             "('OLGames', '网络游戏')",
                             "('Olympics', '奥林匹克运动')",
                             "('Orchestra', '南大交响乐团')",
                             "('OUC', '中国海洋大学')",
                             "('OurCustom', '民俗民风')",
                             "('Ourselves', '百合原创')",
                             "('Overseas', '海外游子')",
                             "('Paint', '涂鸦论坛')",
                             "('PartTimeJob', '兼职工作信息')",
                             "('Party_of_Killer', '杀手的童话')",
                             "('PCGames', '电脑游戏')",
                             "('Peer_Edu', '青春伊甸园')",
                             "('PeerCounseling', '朋辈咨询')",
                             "('People', '人物')",
                             "('PersonalCorpus', '个人文集')",
                             "('PetsEden', '宠物乐园')",
                             "('Philosophy', '哲学与思考')",
                             "('Photography', '摄影艺术')",
                             "('Physics', '物理学')",
                             "('Piano', '钢琴艺术')",
                             "('Pictures', '贴图版')",
                             "('PKU', '北京大学')",
                             "('Politics', '政治科学')",
                             "('PopMusic', '流行音乐天地')",
                             "('Postdoc', '博士后之家')",
                             "('Program', '程序员的休闲室')",
                             "('Psychology', '心理健康')",
                             "('PuKouCampus', '浦园风景线')",
                             "('Python', 'Python语言')",
                             "('QuYi', '曲苑杂谈')",
                             "('Radio', '空中梦想家')",
                             "('Reading', '读书')",
                             "('ReadyForJob', '阳光工作室')",
                             "('RealEstate', '房地产')",
                             "('RedCross', '红十字运动')",
                             "('Renju', '五子连珠')",
                             "('Riddle', '射一射老虎')",
                             "('RockMusic', '摇滚乐世界')",
                             "('RoomChating', '寝室夜话')",
                             "('RunForEver', '田径')",
                             "('Russia', '风雪俄罗斯')",
                             "('S_Astronomy', '天文与空间科学学院')",
                             "('S_Atmosphere', '大气科学学院')",
                             "('S_Business', '商学院')",
                             "('S_Chemistry', '化学化工学院')",
                             "('S_Education', '教育研究院')",
                             "('S_Environment', '环境学院')",
                             "('S_ForeignLang', '外国语学院')",
                             "('S_Geography', '地理学院')",
                             "('S_GOV', '政府管理学院')",
                             "('S_Graduate', '研究生之家')",
                             "('S_Information', '信息管理学院')",
                             "('S_Journalism', '新闻传播学院')",
                             "('S_Law', '法学院')",
                             "('S_LifeScience', '生命科学院')",
                             "('S_Medicine', '医学院')",
                             "('S_MSE', '工程管理学院')",
                             "('S_Sociology', '社会学院')",
                             "('S_Software', '软件学院')",
                             "('SanGuo', '三国风云')",
                             "('SAU', '建筑与城市规划学院')",
                             "('SCDA', '学生职业发展协会')",
                             "('Sculpture', '雕塑艺术')",
                             "('SE_Association', '阳光海岸（华南网友版）')",
                             "('Seasons', '欧美电视剧')",
                             "('SEU', '东南大学')",
                             "('ShanDong', '齐鲁青未了')",
                             "('ShangHai', '寻梦海上花')",
                             "('ShanXi', '三晋梦萦')",
                             "('Shopping', '购物天堂')",
                             "('ShortMessage', '短信大家聊')",
                             "('Shows', '综艺大秀场')",
                             "('SIFE_NJU', '国际大学生企业家联盟')",
                             "('SiGuo', '缥缈四国')",
                             "('Single', '单身一族')",
                             "('SiYuan', '南大思源社')",
                             "('SJ', '升级艺术')",
                             "('SJTU', '上海交通大学')",
                             "('Skating', '溜冰人生')",
                             "('Smoking', '淡烟人生')",
                             "('SoftEng', '软件工程')",
                             "('Software', '软件天地')",
                             "('SPA', '南大学生心理协会')",
                             "('Spanish', '西班牙语')",
                             "('SportsNews', '体坛快讯')",
                             "('Stock', '股市风云')",
                             "('StoneCity', '石头城')",
                             "('StoneStory', '红楼逸梦')",
                             "('Story', '故事会')",
                             "('Sudoku', '快乐数独')",
                             "('SuperGirls', '超级女声')",
                             "('SuQian', '西楚下相')",
                             "('SuZhou', '雨渍东吴')",
                             "('Swimming', '游泳')",
                             "('sysop', '站长的工作室')",
                             "('TableTennis', '乒乓球')",
                             "('Taekwondo', '跆拳道')",
                             "('Taiwan', '宝岛之恋')",
                             "('TaiZhou', '古韵泰州')",
                             "('TCM', '古意中医')",
                             "('Tennis', '网球天地')",
                             "('test', '这是站内测试版')",
                             "('TeX', '科技文献排版')",
                             "('Theoretical_CS', '理论计算机科学')",
                             "('Thesis', '论文')",
                             "('THU', '清华大学')",
                             "('TianJian', '南大天健社')",
                             "('TianJin', '九河下梢天津卫 ')",
                             "('Tibet', '雪域桑烟')",
                             "('Traffic_Info', '交通信息')",
                             "('Train', '汽笛声声')",
                             "('Travel', '遍览天下')",
                             "('TV', '电视')",
                             "('TVGames', '电视游戏')",
                             "('UrbanPlan', '城市规划')",
                             "('US_JP_Research', '美日研究')",
                             "('USTC', '中国科技大学')",
                             "('V_Suggestions', '校长信箱')",
                             "('VC', 'Visual C++ 版')",
                             "('Vegetarian', '素食者')",
                             "('Virus', '可恶可怕的病毒')",
                             "('Volleyball', '排球版')",
                             "('Volunteer', '青年志愿者协会')",
                             "('vote', '本站各项投票与结果')",
                             "('VoteBoard', '选举版')",
                             "('WarAndPeace', '百年好合')",
                             "('WebDesign', '网站设计')",
                             "('WebGames', '网页游戏')",
                             "('WeiQi', '围棋')",
                             "('West_Volunteer', '支教岁月')",
                             "('WesternstyleChess', '国际象棋')",
                             "('WHU', '武汉大学')",
                             "('Wisdom', '儒释道')",
                             "('WorldFootball', '世界足球')",
                             "('WorldNews', '国际新闻')",
                             "('WuShu', '中华武术')",
                             "('WuXi', '梁溪寄畅')",
                             "('XiBei', '壮哉大西北')",
                             "('XiNan', '风起西南')",
                             "('xinhongji', '新鸿基社')",
                             "('XinJiang', '我们新疆亚克西')",
                             "('XJTU', '西安交通大学')",
                             "('XMU', '厦门大学')",
                             "('XuZhou', '古彭汉风')",
                             "('YanCheng', '登瀛渔火')",
                             "('YangTaiChi', '杨式太极拳协会')",
                             "('YangtzeDelta', '长江三角洲发展论坛')",
                             "('YangZhou', '五亭烟雨')",
                             "('YOGA', '南大瑜伽')",
                             "('ZheJiang', '钱江潮')",
                             "('ZhenJiang', '古城镇江')",
                             "('ZhuangXiu', '家居装修')",
                             "('Zjl_Online', '珠江路热线')",
                             "('ZJU', '浙江大学')",};
    }

}
